### ISSUE TITLE
It seems that there are some bug with the code

### ISSUE THREAD

**Issue by Italy2006** [yoon307/CTI#4]
Start experiment cti!                                                                                                        
Train dataset is loaded from ./voc12/train_aug.txt                                                                           
Validation dataset is loaded from ./voc12/train.txt                                                                          
Traceback (most recent call last):                                                                                           
  File "/home/dancer/WeakSupervision/CTI/train_trm.py", line 229, in <module>                                                
    model = getattr(importlib.import_module('models.model_'+args.model), 'model_WSSS')(args, logger)                         
  File "/home/dancer/WeakSupervision/CTI/models/model_CTI.py", line 151, in __init__                                         
    self.net_trm = create_model(                                                                                             
  File "/home/dancer/anaconda3/envs/ddpm/lib/python3.9/site-packages/timm/models/factory.py", line 71, in create_model       
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)                                        
  File "/home/dancer/WeakSupervision/CTI/networks/mctformer.py", line 271, in deit_small_MCTformerV2_CTI                     
    model = MCTformerV2_CTI(                                                                                                 
  File "/home/dancer/WeakSupervision/CTI/networks/mctformer.py", line 103, in __init__                                       
    super().__init__(*args, **kwargs)                                                                                        
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

**Comment by yoon307** [comment]
Hi, this error seems to be the pytorch version issue and you can modify the "pretrained_cfg" by setting to None in your pytorch library. This will handle the issue.
